# 🧩 Reto 1 – Temperatura
**Objetivo:** clasificar la temperatura del agua y evaluar posible estrés térmico.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `temperatura` en `df_temp`.
3. Crea `categoria_temp` con np.where o .loc.
4. Crea `riesgo_termico`.
5. Filtra a `df_caliente` (alta temperatura).
6. Exporta `resultado_temperatura.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo térmico.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/muestras_calidad_agua.csv")

In [6]:
df_temp = df[["sitio", "temperatura"]]

In [3]:
df.head()

                          sitio   pH  oxigeno  temperatura
0                Río Subachoque  7.2      7.8         18.5
1   Quebrada Honda (Facatativá)  6.3      6.2         19.4
2          Río Botello (Madrid)  6.8      5.9         22.7
3  Afluente San José (El Rosal)  7.9      8.3         20.1
4                   Río Villeta  8.7      6.1         28.3

In [7]:
df_temp

                           sitio  temperatura
0                 Río Subachoque         18.5
1    Quebrada Honda (Facatativá)         19.4
2           Río Botello (Madrid)         22.7
3   Afluente San José (El Rosal)         20.1
4                    Río Villeta         28.3
5  Quebrada Cune (San Francisco)         25.2
6            Río Tobia (Nocaima)         26.9
7       Quebrada Negra (La Vega)         24.4
8          Río Bahamón (Sasaima)         27.6
9        Río Guayuriba (La Mesa)         30.5

In [8]:
df_temp["categoria_temp"] = np.where(
    df_temp["temperatura"] > 25,
    "Alta",
    "Normal"
)

In [9]:
df_temp.head()

                          sitio  temperatura categoria_temp
0                Río Subachoque         18.5         Normal
1   Quebrada Honda (Facatativá)         19.4         Normal
2          Río Botello (Madrid)         22.7         Normal
3  Afluente San José (El Rosal)         20.1         Normal
4                   Río Villeta         28.3           Alta

In [10]:
df_temp["riesgo_termico"] = np.where(
    df_temp["temperatura"] > 28,
    "Sí",
    "No"
)

In [11]:
df_temp.head()

                          sitio  temperatura categoria_temp riesgo_termico
0                Río Subachoque         18.5         Normal             No
1   Quebrada Honda (Facatativá)         19.4         Normal             No
2          Río Botello (Madrid)         22.7         Normal             No
3  Afluente San José (El Rosal)         20.1         Normal             No
4                   Río Villeta         28.3           Alta             Sí

In [12]:
df_caliente = df_temp[df_temp["categoria_temp"] == "Alta"]

In [13]:
df_caliente

                           sitio  temperatura categoria_temp riesgo_termico
4                    Río Villeta         28.3           Alta             Sí
5  Quebrada Cune (San Francisco)         25.2           Alta             No
6            Río Tobia (Nocaima)         26.9           Alta             No
8          Río Bahamón (Sasaima)         27.6           Alta             No
9        Río Guayuriba (La Mesa)         30.5           Alta             Sí

In [14]:
df_temp.to_csv("../data/resultado_temperatura.csv", index=False)

In [15]:
porcentaje = (df_temp["riesgo_termico"] == "Sí").mean() * 100

print("Porcentaje de sitios con riesgo térmico:", porcentaje, "%")

Porcentaje de sitios con riesgo térmico: 20.0 %

El análisis de temperatura permitió clasificar los sitios según sus condiciones térmicas e identificar posibles riesgos asociados al aumento de la temperatura del agua. Mediante el uso de estructuras condicionales y funciones de NumPy fue posible categorizar los registros y detectar sitios con potencial estrés térmico.

Los resultados muestran que algunos cuerpos de agua presentan temperaturas elevadas, lo que podría afectar los organismos acuáticos y alterar el equilibrio ecológico. Además, el cálculo del porcentaje de sitios con riesgo térmico facilitó una mejor interpretación de la situación ambiental evaluada.

Este reto permitió fortalecer habilidades en manipulación de datos, uso de condicionales y análisis ambiental mediante programación en Python.